language: java
jdk:
  - openjdk8

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build --exclude-task test"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspect.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/GRAP_BackEnd.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yun-springboot
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    on:
      branch: main
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yun-springboot
    key: GRAP_BackEnd.zip
    bundle-type: zip
    application: grap
    deployment_group: grap-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
      - syoun602@gmail.com

