language: java
jdk:
  - openjdk8

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build --exclude-task test"

before_deploy:
  - zip -r GRAP_BackEnd *
  - mkdir -p deploy
  - mv GRAP_BackEnd.zip deploy/GRAP_BackEnd.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yun-springboot
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    on:
      branch: main
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - syoun602@gmail.com

